# Noctalia v5 Configuration

[shell]
font_family = "JetBrainsMono Nerd Font"
clipboard_enabled = true

[shell.panel]
transparency_mode = "soft"
wallpaper_position = "center"

[shell.screenshot]
directory = "@HOME@/Pictures/Screenshots"
remember_last_region = true

[backdrop]
blur_intensity = 0.55
tint_intensity = 0.4

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"
builtin = "Rosé Pine"

[theme.templates]
enable_builtin_templates = true
builtin_ids = [
  "btop",
  "cava",
  "gtk3",
  "gtk4",
  "helix",
  "niri",
  "qt",
  "starship",
  "wezterm",
]
enable_community_templates = true
community_ids = [
  "antigravity",
  "bat",
  "discord",
  "fastfetch",
  "heroiclauncher",
  "obs",
  "opencode",
  "vscode",
  "yazi",
  "zed",
  "zen-browser",
]

[wallpaper]
enabled = true
fill_mode = "crop"
directory = "@HOME@/Pictures/Wallpapers"
transition = ["fade", "honeycomb", "stripes"]
transition_on_startup = true

[dock]
enabled = true
background_opacity = 1.0
border = "secondary"
concave_edge_corners = false
icon_size = 35
launcher_icon = "rocket"
launcher_position = "end"
main_axis_padding = 8
margin_edge = 7
reserve_space = false
show_dots = true
show_instance_count = false
smart_auto_hide = true

[bar.main]
position = "top"
thickness = 34
background_opacity = 0.8
radius = 12
margin_ends = 4
margin_edge = 4
padding = 6
widget_spacing = 6
scale = 0.9
capsule = true
capsule_opacity = 1.0
font_family = "JetBrainsMono Nerd Font"

start = ["launcher", "clock", "sysmon", "active_window", "media"]
center = ["workspaces"]
end = [
  "group:g1",
  "keyboard_layout",
  "tray",
  "notifications",
  "battery",
  "blackbartblues/audio-switcher:widget",
  "brightness",
  "network",
  "control_center",
]

[[bar.main.capsule_group]]
id = "g1"
enabled = true
accordion = false
accordion_direction = "end"
fill = "surface"
foreground = "on_tertiary"
opacity = 1.0
padding = 8.0
members = ["network_rx", "network_tx"]

[widget.clock]
format = "{:%I:%M %p %a, %b %d}"

[widget.sysmon]
stat = "cpu_usage"
show_glyph = true
show_value = true
visualization = "none"

[widget.battery]
device = "BAT1"
display_mode = "glyph"
show_label = true
hide_when_plugged = false

[widget.tray]
drawer = true

[widget.keyboard_layout]
show_glyph = false
show_label = true

[widget.network]
show_label = false

[hooks]
started = "@ASUS_AURA_SYNC@"
colors_changed = ["@ASUS_AURA_SYNC@"]
wallpaper_changed = ["@ASUS_AURA_SYNC@ \"$NOCTALIA_WALLPAPER_PATH\""]
theme_mode_changed = ["@ASUS_AURA_SYNC@"]

[plugins]
enabled = [
  "blackbartblues/audio-switcher",
  "kenn/keybind-cheatsheet",
  "noctalia/wallhaven"
]
auto_update = "all"
